name: 'Stu & Andrea Wedding'
favicon: null
layout_spectrum: 0.33053
typography_spectrum: 0.2586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bababa'
    - '#df0000'
    - '#008acc'
    - '#eb4e3a'
    - '#5d5d5d'
  brandStrength: 0.4500540017616004
  lightness: 0.7573335249908268
  saturation: 0.710931102745235
  rhythmicContrast: 0.8932658804114908
purpose: []
